### ISSUE TITLE
React.createClass() 调用传递的参数是function 报错

### ISSUE THREAD

**Issue by jsers** [dora-js/dora-plugin-hmr#2]
```
Module build failed: TypeError: /Users/xxx.jsx: Cannot read property 'find' of undefined
    at find (/Users/daixiaqing/git/src/rc-common-demo/node_modules/array-find/find.js:5:17)
    at getDisplayName (/Users/daixiaqing/git/src/rc-common-demo/node_modules/babel-plugin-react-transform/lib/index.js:33:44)
    at Object.CallExpression (/Users/daixiaqing/git/src/rc-common-demo/node_modules/babel-plugin-react-transform/lib/index.js:110:27)
    at NodePath._call (/Users/daixiaqing/git/src/rc-common-demo/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/daixiaqing/git/src/rc-common-demo/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/daixiaqing/git/src/rc-common-demo/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/daixiaqing/git/src/rc-common-demo/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (/Users/daixiaqing/git/src/rc-common-demo/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/daixiaqing/git/src/rc-common-demo/node_modules/babel-traverse/lib/context.js:197:19)
    at Function.traverse.node (/Users/daixiaqing/git/src/rc-common-demo/node_modules/babel-traverse/lib/index.js:139:17)
```

经过排除，发现只要React.createClass() 调用传递的参数是function就报错。
估计是babel-plugin-react-transform的问题。
好吧，虽然这种写法不好，但是这样报错感觉不太合理。

**Comment by jsers** [comment]
好吧，是babel-plugin-react-transform的bug
https://github.com/gaearon/babel-plugin-react-transform/issues/61
